ALTER TABLE presets DROP COLUMN IF EXISTS mode;

ALTER TABLE presets
  ADD COLUMN IF NOT EXISTS lumbar_heat INTEGER NOT NULL DEFAULT 0
    CHECK (lumbar_heat BETWEEN 0 AND 3),
  ADD COLUMN IF NOT EXISTS upper_back_heat INTEGER NOT NULL DEFAULT 0
    CHECK (upper_back_heat BETWEEN 0 AND 3),
  ADD COLUMN IF NOT EXISTS leg_heat INTEGER NOT NULL DEFAULT 0
    CHECK (leg_heat BETWEEN 0 AND 3);

ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS chair_angle_degrees INTEGER,
  ADD COLUMN IF NOT EXISTS lumbar_heat INTEGER,
  ADD COLUMN IF NOT EXISTS upper_back_heat INTEGER,
  ADD COLUMN IF NOT EXISTS leg_heat INTEGER,
  ADD COLUMN IF NOT EXISTS light_mode TEXT,
  ADD COLUMN IF NOT EXISTS light_color TEXT;
